function canvas(): string { switch (tab) {
    case 'network': return networkView();
    case 'map': return mapView();
    case 'timeline': return timelineView();
    case 'brief': return `<div class="brief-view"><div class="section-eyebrow">TEMPLATE / CURRENT ADMITTED CORPUS / NO MODEL CALL</div><h2>Traceable evidence brief</h2>${answerView(workspace!.baseline)}<p class="small muted">This view updates when a source is excluded. It is separate from the shared accepted assessment.</p></div>`;
    case 'training': return trainingView();
    default: return '';
} }
function networkView(): string { const g = workspace!.graph; const pos: Record<string, [
    number,
    number
]> = { 'programme': [115, 290], 'PCC-EQUIPMENT-P00004896': [355, 95], 'PCC-OPERATIONS-047c84': [355, 290], 'PORT-PCC-REPORTED-MILESTONE': [355, 510], 'CF-AWARD': [645, 80], 'FTS-PIN': [645, 210], 'FTS-TENDER': [645, 320], 'FTS-CORRECTION': [645, 425], 'PORT-STATEMENT': [645, 535] }; const edges = g.edges.map(e => { const a = pos[e.source], b = pos[e.target]; if (!a || !b)
    return ''; const correction = e.kind === 'title_correction'; return `<g class="edge ${correction ? 'correction' : ''}"><title>${esc(e.kind + ': ' + e.locator + ' [' + e.source_version_id + ']')}</title><path d="${correction ? `M ${a[0] + 90} ${a[1] + 15} C ${a[0] + 130} ${a[1] + 15}, ${b[0] + 130} ${b[1] - 15}, ${b[0] + 90} ${b[1] - 15}` : `M ${a[0] + 75} ${a[1]} C ${a[0] + 140} ${a[1]}, ${b[0] - 150} ${b[1]}, ${b[0] - 96} ${b[1]}`}"/><circle cx="${b[0] - 96}" cy="${b[1]}" r="3"/></g>`; }).join(''); const nodes = g.nodes.map(n => { const p = pos[n.id]; if (!p)
    return ''; const doc = n.kind === 'document'; const short = shortNames[n.id] || n.label; const lines = short.split(' '); let first = '', second = ''; for (const word of lines) {
    if ((first + ' ' + word).trim().length <= 22 && !second)
        first = (first + ' ' + word).trim();
    else
        second = (second + ' ' + word).trim();
} return `<g class="graph-node ${n.kind} ${selectedSource === n.id ? 'chosen' : ''}" transform="translate(${p[0]},${p[1]})" ${doc ? `data-action="select" data-id="${esc(n.id)}" tabindex="0" role="button" aria-label="Inspect ${esc(short)}"` : ''}><title>${esc(n.label)}</title><rect x="-96" y="-37" width="192" height="74" rx="10"/><circle cx="-76" cy="-14" r="4"/><text class="node-type" x="-63" y="-10">${doc ? esc(n.id) : n.kind === 'case' ? 'INVESTIGATION' : 'DECLARED ORIGIN'}</text><text x="-77" y="12">${esc(first)}</text>${second ? `<text x="-77" y="28">${esc(second)}</text>` : ''}</g>`; }).join(''); return `<div class="canvas-heading"><div><h2>Evidence network</h2><p>Select a document to inspect its source. Lines represent provenance, not proof.</p></div><div class="zoom-controls">${action('zoom-out', '−', 'aria-label="Zoom out"')}${action('zoom-in', '+', 'aria-label="Zoom in"')}</div></div><div class="graph-wrap"><svg id="evidence-graph" viewBox="0 0 ${840 / zoom} ${630 / zoom}" role="img" aria-label="Source-provenance network for the admitted evidence"><defs><pattern id="dots" x="0" y="0" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1"/></pattern></defs><rect width="1600" height="1200" fill="url(#dots)" class="dot-grid"/>${edges}${nodes}</svg>${g.nodes.length ? '' : '<div class="empty-state">No admitted evidence. Reinstate a source to rebuild this network.</div>'}</div><div class="graph-legend"><span><i class="line-key"></i> Case grouping / common origin</span><span><i class="line-key correction"></i> Title correction</span><span>No independence assumption</span></div><div class="insight-strip"><span class="insight-number">01</span><div><strong>${workspace!.sources.filter(s => !s.excluded && s.origin_group.includes("OPERATIONS")).length} admitted operations notice(s) share one declared origin.</strong><p>${workspace!.session.mode === 'HISTORICAL_RECONSTRUCTION' ? 'Only documents available by this cutoff are displayed.' : 'A correction or a repeated report does not automatically add independent support.'}</p></div></div>`; }
function detailView(): string { if (!detail)
    return `<div class="drawer-empty"><div class="eyebrow">EVIDENCE DRAWER</div><h2>Select a source</h2><p>Inspect its exact retained passages and provenance here.</p></div>`; return `<div class="drawer-top"><div class="eyebrow">SOURCE INSPECTOR</div>${statusTag(detail.representation === 'original_http_capture' ? 'Original HTTP capture' : 'Real / curated extract', detail.representation === 'original_http_capture' ? 'good' : 'warn')}<h2>${esc(shortNames[detail.id] || detail.display_title)}</h2><p>${esc(detail.publisher)}</p></div><dl class="metadata"><div><dt>Published</dt><dd>${esc(date(detail.publisher_timestamp || detail.publisher_date))}</dd></div><div><dt>Captured</dt><dd>${detail.acquired_at ? esc(date(detail.acquired_at)) : 'Not an original HTTP capture'}</dd></div><div><dt>Coverage</dt><dd>${esc(detail.coverage)}</dd></div><div><dt>Origin</dt><dd class="mono">${esc(detail.origin_group)}</dd></div></dl><a class="source-link" href="${safeLink(detail.url)}" target="_blank" rel="noopener noreferrer">Open original publication ↗</a><div class="segments">${detail.segments.map(s => `<section id="segment-${esc(s.id)}" class="segment"><div class="segment-label">${esc(s.locator)}</div><blockquote>${esc(s.text)}</blockquote><div class="hash">SHA-256 ${esc(s.sha256.slice(0, 16))}…</div></section>`).join('')}</div><div class="drawer-foot"><span>Version</span><code>${esc(detail.version_id)}</code><p>${esc(detail.licence)}</p>${detail.id === 'CF-AWARD' ? '<div class="callout warn">Data-quality issue: a structured zero is not proof of a free contract.</div>' : ''}${detail.id === 'FTS-CORRECTION' ? '<div class="callout">Title repair only. No numeric forecast change is inferred.</div>' : ''}</div>`; }
function mapView(): string { const loc = workspace!.case.location; if (!loc)
    return `<div class="empty-state"><h2>Current-location layer withheld</h2><p>The visitor-directions source was inspected later. It is not admitted into this historical reconstruction.</p>${action('tab', 'Return to evidence network', 'data-tab="network"')}</div>`; return `<div class="canvas-heading"><div><h2>Project context</h2><p>Publisher-supplied visitor directions, not an installation survey.</p></div>${action('map-tiles', mapEnabled ? 'Reload map tiles' : 'Load OpenStreetMap tiles', '', 'quiet')}</div><div id="map-canvas" class="map-canvas"><div class="coordinate-grid" aria-hidden="true"></div><div id="tiles" class="tile-layer"></div><button class="map-pin" data-action="select" data-id="FTS-TENDER" aria-label="Inspect port location evidence"><span class="pin-ring"></span><span class="pin-core"></span><span class="pin-label">Portsmouth International Port</span></button><div class="map-status" id="map-status">Base map not loaded. The sourced directions coordinate remains available below.</div></div><div class="map-attribution">${mapEnabled ? '<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors</a> · ' : ' '}Network/list views remain available without map tiles.</div><div class="location-card"><span class="eyebrow">PUBLISHER DIRECTIONS PIN</span><h3>${esc(loc.name)}</h3><div class="coordinates">${loc.lat.toFixed(6)}° N &nbsp; ${Math.abs(loc.lon).toFixed(6)}° W</div><p>${esc(loc.precision)}</p><a href="${safeLink(loc.source_url)}" target="_blank" rel="noopener noreferrer">Source: Portsmouth International Port, “Find us” ↗</a><p class="small muted">Reviewed ${esc(loc.reviewed_on)}. No live vessel tracking.</p></div>`; }
function loadTiles(): void { const loc = workspace!.case.location; if (!loc)
    return; const holder = document.querySelector<HTMLDivElement>('#tiles')!; const status = document.querySelector<HTMLDivElement>('#map-status')!; const z = 13, n = 2 ** z, x = (loc.lon + 180) / 360 * n, y = (1 - Math.asinh(Math.tan(loc.lat * Math.PI / 180)) / Math.PI) / 2 * n; const width = holder.clientWidth, height = holder.clientHeight; let loaded = 0, failed = 0, total = 0; for (let tx = Math.floor(x) - 2; tx <= Math.floor(x) + 2; tx++)
    for (let ty = Math.floor(y) - 1; ty <= Math.floor(y) + 1; ty++) {
        const left = width / 2 + (tx - x) * 256, top = height / 2 + (ty - y) * 256;
        if (left > width || left + 256 < 0 || top > height || top + 256 < 0)
            continue;
        total++;
        const image = document.createElement('img');
        image.alt = '';
        image.width = 256;
        image.height = 256;
        image.style.left = left + 'px';
        image.style.top = top + 'px';
        image.onload = () => { loaded++; status.textContent = failed ? 'Some tiles unavailable; evidence remains accessible.' : loaded === total ? 'Map context loaded. Directions pin only.' : 'Loading map context…'; };
        image.onerror = () => { failed++; image.remove(); status.textContent = 'Map tiles unavailable. Use the sourced coordinate and evidence network.'; };
        image.src = `https://tile.openstreetmap.org/${z}/${tx}/${ty}.png`;
        holder.append(image);
    } status.textContent = 'Requesting OpenStreetMap tiles…'; }
function timelineView(): string { const items = [...workspace!.sources].filter(s => !s.excluded).sort((a, b) => (a.publisher_timestamp || a.publisher_date || '9999').localeCompare(b.publisher_timestamp || b.publisher_date || '9999')); return `<div class="canvas-heading"><div><h2>Publication timeline</h2><p>Publication, retrieval and admission are distinct events.</p></div></div><div class="replay-controls"><span class="eyebrow">RECONSTRUCT 5 OCTOBER 2024</span><div>${action('before', '15:22 UTC · before correction', '', 'chip')}${action('after', '15:26 UTC · after correction', '', 'chip')}${action('current', 'Current investigation', '', 'chip')}</div><p>These are retrospective source extracts. No contemporaneous capture is claimed.</p></div><div class="timeline-list">${items.map(s => `<article class="timeline-item"><div class="timeline-point"></div><time>${esc(date(s.publisher_timestamp || s.publisher_date))}</time><button data-action="select" data-id="${esc(s.id)}">${esc(shortNames[s.id])}</button><p>${esc(label(s.source_type || 'publication'))} · inspect the selected version for the retained wording.</p><span>${esc(s.representation === 'original_http_capture' ? 'Original HTML retained' : 'Curated extract; not captured at publication')}</span></article>`).join('')}</div>`; }
function answerView(answer: Answer): string { return `<div class="statements">${answer.statements.map((s, i) => `<article class="statement"><div>${statusTag(label(s.kind), s.kind === 'data_quality_issue' ? 'warn' : 'muted')}<span class="statement-number">${String(i + 1).padStart(2, '0')}</span></div><p>${esc(s.text)}</p><div class="citations">${s.citations.map(c => action('citation', esc(c.source_version_id.split('-seed')[0].split('-http')[0]) + ' · ' + esc(c.segment_id), `data-version="${esc(c.source_version_id)}" data-segment="${esc(c.segment_id)}"`, 'citation')).join('')}</div></article>`).join('')}</div><div class="uncertainties"><h3>What remains unknown</h3>${answer.uncertainties.map(s => `<p>${esc(s)}</p>`).join('')}<h3>Evidence to seek next</h3>${answer.next_evidence.map(s => `<p>${esc(s)}</p>`).join('')}</div>`; }
function draftView(): string { if (!draft?.answer)
    return ''; return `<section class="draft-panel" id="draft-panel"><div class="draft-heading"><div><div class="eyebrow">${draft.inference ? 'FRESH MODEL DRAFT / RETAINED EVIDENCE' : 'TEMPLATE BRIEF / ZERO MODEL CALLS'}</div><h2>Reviewable briefing</h2></div>${user?.role === 'owner' ? action('review', 'Review for acceptance', '', 'primary') : statusTag('Reviewer sandbox')}</div>${answerView(draft.answer)}${draft.runs?.length ? `<div class="run-records">${draft.runs.map(r => `<p>${esc(r.phase)} · ${esc(r.returned_model || 'model not returned')} · ${esc(date(r.started_at))} · cost ${r.cost === null ? esc(r.cost_status) : '$' + r.cost.toFixed(5)}</p>`).join('')}</div>` : ''}${draft.challenge?.answer ? `<details><summary>Second-pass challenge (not an independent human review)</summary>${answerView(draft.challenge.answer)}</details>` : ''}${draft.challenge_error ? `<div class="callout warn">The first draft is retained. Challenge failed: ${esc(label(draft.challenge_error))}</div>` : ''}<p class="small muted">Quotations located ≠ claims proven. Acceptance records the owner’s explicit support review.</p></section>`; }
function trainingView(): string { return `<div class="training-view"><div class="training-banner">SYNTHETIC TRAINING ONLY · NOT THE PORTSMOUTH ASSESSMENT</div><h2>What happens when evidence is corrected?</h2><p>A declared likelihood ratio (relative support for a hypothesis) changes the odds. A revised record replaces its old factor.</p><div class="training-inputs"><label>Starting probability<input id="prior" type="number" min="0.01" max="0.99" step="0.01" value="0.5"></label><label>Initial likelihood ratio<input id="initial-lr" type="number" min="0.01" max="1000" step="0.1" value="3"></label><label>Replacement ratio<input id="replacement-lr" type="number" min="0.01" max="1000" step="0.1" value="0.5"></label></div>${action('calculate', 'Calculate sensitivity', '', 'primary')}<div id="sensitivity-output"><p class="muted">Enter assumptions and calculate. This uses server-side arithmetic, not AI confidence.</p></div><div class="callout warn">Duplicate reports from the same origin are not multiplied. No training result is admitted to the real evidence graph or a real-case export.</div></div>`; }
const tourSteps = [['Start with a real record', 'Open the equipment award and compare its two value fields. The interface shows the retained text, source and version.'], ['Inspect the chronology', 'Switch between the two October cutoffs. The correction is withheld before its recorded publication time.'], ['Follow the correction', 'The actual notice changes “Por” to “Port”. It does not establish a changed operating milestone.'], ['Remove a source', 'Use a source’s minus control. The brief and graph must lose that source’s support without rewriting the shared accepted assessment.'], ['Leave an audit trail', 'Compile a template briefing, inspect its citations, then export. Drive status stays local-only until upload and readback succeed.']];
function tourView(): string { const step = tourSteps[tour]; return `<section class="tour-panel"><span class="tour-number">${tour + 1} / ${tourSteps.length}</span><div><strong>${step[0]}</strong><p>${step[1]}</p></div><div>${action('tour-next', tour === 4 ? 'Finish' : 'Next ' + icon('arrow'), '', 'primary')}${action('tour-close', icon('close'), 'aria-label="Close guided demo"', 'quiet')}</div></section>`; }
